### ISSUE TITLE
3 Body Animated - subs

### ISSUE THREAD

**Issue by threebodysuperfan** [IzzyData/ThreeBodyAnimated#1]
Greetings! I was wondering when the edited translation subs would be available for the final 2 episodes? Thanks so much for your work and efforts so far, it is appreciated

**Comment by IzzyData** [comment]
Apologies. I'll do my best to get them both done tomorrow.

**Comment by threebodysuperfan** [comment]
That would be amazing, thank you very much!! My friends and I are excited to finish the series
